### ISSUE TITLE
训练过程中出现问题

### ISSUE THREAD

**Issue by xskxskxsk** [yun-liu/FastSaliency#5]
![image](https://user-images.githubusercontent.com/72691043/127332929-4d1151eb-ccde-4c6d-8458-2e3344934cf1.png)
一个epoch结束后，Iter [2081/2108]执行addBatch，出现图示错误是什么原因呢

**Comment by xskxskxsk** [comment]
是在SAMNET训练过程中

**Comment by xskxskxsk** [comment]
已经解决了！

**Comment by SanQi888** [comment]
你好，请问代码调通了吗
